// ⚠️ DEMO DATA — Not real accessibility claims about actual businesses
import type { Place, Report, Photo, User } from './types';

export const DEMO_PLACES: Place[] = [
  {
    id: 'place-001',
    name: 'Coimbatore Medical College Hospital',
    category: 'hospital',
    address: 'Avinashi Road, Peelamedu, Coimbatore 641014',
    lat: 11.0218,
    lng: 76.9847,
    accessibilityScore: 78,
    confidenceScore: 91,
    lastVerified: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    reportCount: 14,
    verificationCount: 9,
    photoCount: 6,
    isDemo: true,
    businessVerified: false,
    status: 'partial',
    features: [
      { id: 'f1', name: 'entrance', label: 'Entrance', status: 'good', note: 'Step-free main entrance', weight: 0.2 },
      { id: 'f2', name: 'ramp', label: 'Ramp', status: 'partial', note: 'Available but steep in south wing', weight: 0.2 },
      { id: 'f3', name: 'lift', label: 'Lift', status: 'good', note: 'Operational, wide doors', weight: 0.1 },
      { id: 'f4', name: 'toilet', label: 'Accessible Toilet', status: 'partial', note: 'Available, sometimes locked', weight: 0.15 },
      { id: 'f5', name: 'parking', label: 'Parking', status: 'good', note: 'Dedicated accessible bays marked', weight: 0.1 },
      { id: 'f6', name: 'footpath', label: 'Footpath', status: 'partial', note: 'Uneven near OPD block', weight: 0.1 },
      { id: 'f7', name: 'door', label: 'Door Width', status: 'good', note: 'Automatic sliding doors', weight: 0.1 },
      { id: 'f8', name: 'transport', label: 'Transport Access', status: 'good', note: 'Bus stop 50m away', weight: 0.05 },
    ],
  },
  {
    id: 'place-002',
    name: 'Brookefields Mall',
    category: 'shop',
    address: 'Brookefields, Krishnaswamy Road, Coimbatore 641044',
    lat: 11.0054,
    lng: 76.9651,
    accessibilityScore: 88,
    confidenceScore: 85,
    lastVerified: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    reportCount: 8,
    verificationCount: 7,
    photoCount: 10,
    isDemo: true,
    businessVerified: true,
    status: 'good',
    features: [
      { id: 'f1', name: 'entrance', label: 'Entrance', status: 'good', note: 'Automatic doors, step-free', weight: 0.2 },
      { id: 'f2', name: 'ramp', label: 'Ramp', status: 'good', note: 'Gentle slope at all entrances', weight: 0.2 },
      { id: 'f3', name: 'lift', label: 'Lift', status: 'good', note: 'Multiple lifts on all floors', weight: 0.1 },
      { id: 'f4', name: 'toilet', label: 'Accessible Toilet', status: 'good', note: 'On every floor, unlocked', weight: 0.15 },
      { id: 'f5', name: 'parking', label: 'Parking', status: 'good', note: 'Ground floor bays near lift', weight: 0.1 },
      { id: 'f6', name: 'footpath', label: 'Footpath', status: 'partial', note: 'External footpath uneven', weight: 0.1 },
      { id: 'f7', name: 'door', label: 'Door Width', status: 'good', note: 'Wide doorways throughout', weight: 0.1 },
      { id: 'f8', name: 'transport', label: 'Transport Access', status: 'good', note: 'Bus stop at entrance', weight: 0.05 },
    ],
  },
  {
    id: 'place-003',
    name: 'Gandhipuram Bus Terminal',
    category: 'bus_stop',
    address: 'Gandhipuram, Coimbatore 641012',
    lat: 11.0168,
    lng: 76.9558,
    accessibilityScore: 34,
    confidenceScore: 78,
    lastVerified: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    reportCount: 22,
    verificationCount: 15,
    photoCount: 8,
    isDemo: true,
    businessVerified: false,
    status: 'poor',
    features: [
      { id: 'f1', name: 'entrance', label: 'Entrance', status: 'poor', note: 'Steps at all main entrances', weight: 0.2 },
      { id: 'f2', name: 'ramp', label: 'Ramp', status: 'poor', note: 'No ramp, makeshift plank in use', weight: 0.2 },
      { id: 'f3', name: 'lift', label: 'Lift', status: 'poor', note: 'No lift available', weight: 0.1 },
      { id: 'f4', name: 'toilet', label: 'Accessible Toilet', status: 'poor', note: 'No accessible toilet', weight: 0.15 },
      { id: 'f5', name: 'parking', label: 'Parking', status: 'partial', note: 'Drop zone available', weight: 0.1 },
      { id: 'f6', name: 'footpath', label: 'Footpath', status: 'poor', note: 'Heavily occupied, broken', weight: 0.1 },
      { id: 'f7', name: 'door', label: 'Door Width', status: 'partial', note: 'Some platforms accessible', weight: 0.1 },
      { id: 'f8', name: 'transport', label: 'Transport Access', status: 'good', note: 'Central hub', weight: 0.05 },
    ],
  },
  {
    id: 'place-004',
    name: 'PSG College of Technology',
    category: 'college',
    address: 'Avinashi Road, Peelamedu, Coimbatore 641004',
    lat: 11.0291,
    lng: 76.9948,
    accessibilityScore: 62,
    confidenceScore: 72,
    lastVerified: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    reportCount: 6,
    verificationCount: 4,
    photoCount: 3,
    isDemo: true,
    businessVerified: false,
    status: 'partial',
    features: [
      { id: 'f1', name: 'entrance', label: 'Entrance', status: 'good', note: 'Main gate step-free', weight: 0.2 },
      { id: 'f2', name: 'ramp', label: 'Ramp', status: 'partial', note: 'Some buildings have ramps, not all', weight: 0.2 },
      { id: 'f3', name: 'lift', label: 'Lift', status: 'partial', note: 'Lift in main block only', weight: 0.1 },
      { id: 'f4', name: 'toilet', label: 'Accessible Toilet', status: 'partial', note: 'One accessible toilet near admin', weight: 0.15 },
      { id: 'f5', name: 'parking', label: 'Parking', status: 'partial', note: 'No dedicated accessible bays', weight: 0.1 },
      { id: 'f6', name: 'footpath', label: 'Footpath', status: 'good', note: 'Wide internal pathways', weight: 0.1 },
      { id: 'f7', name: 'door', label: 'Door Width', status: 'partial', note: 'Older blocks have narrow doors', weight: 0.1 },
      { id: 'f8', name: 'transport', label: 'Transport Access', status: 'good', note: 'Multiple buses stop nearby', weight: 0.05 },
    ],
  },
  {
    id: 'place-005',
    name: 'Saravana Bhavan Restaurant',
    category: 'restaurant',
    address: 'DB Road, R.S. Puram, Coimbatore 641002',
    lat: 10.9989,
    lng: 76.9584,
    accessibilityScore: 55,
    confidenceScore: 65,
    lastVerified: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    reportCount: 4,
    verificationCount: 2,
    photoCount: 2,
    isDemo: true,
    businessVerified: false,
    status: 'partial',
    features: [
      { id: 'f1', name: 'entrance', label: 'Entrance', status: 'partial', note: 'One step at entrance, handrail present', weight: 0.2 },
      { id: 'f2', name: 'ramp', label: 'Ramp', status: 'poor', note: 'No ramp', weight: 0.2 },
      { id: 'f3', name: 'lift', label: 'Lift', status: 'poor', note: 'No lift, ground floor only', weight: 0.1 },
      { id: 'f4', name: 'toilet', label: 'Accessible Toilet', status: 'poor', note: 'Standard toilet, not accessible', weight: 0.15 },
      { id: 'f5', name: 'parking', label: 'Parking', status: 'partial', note: 'Street parking only', weight: 0.1 },
      { id: 'f6', name: 'footpath', label: 'Footpath', status: 'partial', note: 'Narrow footpath with hawkers', weight: 0.1 },
      { id: 'f7', name: 'door', label: 'Door Width', status: 'good', note: 'Wide entrance', weight: 0.1 },
      { id: 'f8', name: 'transport', label: 'Transport Access', status: 'good', note: 'Bus stop 100m', weight: 0.05 },
    ],
  },
  {
    id: 'place-006',
    name: 'District Collectorate Office',
    category: 'office',
    address: 'Collectorate Campus, Coimbatore 641018',
    lat: 11.0042,
    lng: 76.9660,
    accessibilityScore: 0,
    confidenceScore: 45,
    lastVerified: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    reportCount: 2,
    verificationCount: 1,
    photoCount: 1,
    isDemo: true,
    businessVerified: false,
    status: 'unverified',
    features: [
      { id: 'f1', name: 'entrance', label: 'Entrance', status: 'unverified', note: 'No recent data', weight: 0.2 },
      { id: 'f2', name: 'ramp', label: 'Ramp', status: 'unverified', note: 'No recent data', weight: 0.2 },
      { id: 'f3', name: 'lift', label: 'Lift', status: 'unverified', note: 'No recent data', weight: 0.1 },
      { id: 'f4', name: 'toilet', label: 'Accessible Toilet', status: 'unverified', note: 'No recent data', weight: 0.15 },
      { id: 'f5', name: 'parking', label: 'Parking', status: 'unverified', note: 'No recent data', weight: 0.1 },
      { id: 'f6', name: 'footpath', label: 'Footpath', status: 'unverified', note: 'No recent data', weight: 0.1 },
      { id: 'f7', name: 'door', label: 'Door Width', status: 'unverified', note: 'No recent data', weight: 0.1 },
      { id: 'f8', name: 'transport', label: 'Transport Access', status: 'unverified', note: 'No recent data', weight: 0.05 },
    ],
  },
];

export const DEMO_REPORTS: Report[] = [
  {
    id: 'report-001',
    placeId: 'place-003',
    placeName: 'Gandhipuram Bus Terminal',
    userId: 'user-002',
    userName: 'Priya Krishnan',
    issueType: 'steps_at_entrance',
    description: 'All three main entrances have steps with no ramp alternative. Have to use a dangerous side path.',
    lat: 11.0168,
    lng: 76.9558,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    confirmCount: 12,
    denyCount: 2,
    status: 'open',
    userVerification: null,
  },
  {
    id: 'report-002',
    placeId: 'place-001',
    placeName: 'Coimbatore Medical College Hospital',
    userId: 'user-003',
    userName: 'Rajan Selvam',
    issueType: 'toilet_locked',
    description: 'Accessible toilet in OPD block is locked. Staff say key is with duty nurse but hard to locate.',
    lat: 11.0218,
    lng: 76.9847,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    confirmCount: 7,
    denyCount: 1,
    status: 'open',
    userVerification: null,
  },
  {
    id: 'report-003',
    placeId: 'place-001',
    placeName: 'Coimbatore Medical College Hospital',
    userId: 'user-004',
    userName: 'Meena Subramani',
    issueType: 'ramp_steep',
    description: 'South wing ramp is too steep — difficult to self-propel. Slope is approximately 1:5.',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    confirmCount: 5,
    denyCount: 0,
    status: 'open',
    userVerification: null,
  },
  {
    id: 'report-004',
    placeId: 'place-005',
    placeName: 'Saravana Bhavan Restaurant',
    userId: 'user-002',
    userName: 'Priya Krishnan',
    issueType: 'steps_at_entrance',
    description: 'One step at entrance with no alternative. Staff helped lift my chair but this is not reliable.',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    confirmCount: 3,
    denyCount: 1,
    status: 'open',
    userVerification: null,
  },
  {
    id: 'report-005',
    placeId: 'place-003',
    placeName: 'Gandhipuram Bus Terminal',
    userId: 'user-005',
    userName: 'Vikram Anand',
    issueType: 'waterlogging',
    description: 'After rain, entire platform area floods. Extremely difficult to navigate.',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    confirmCount: 4,
    denyCount: 0,
    status: 'open',
    isTemporary: true,
    expiresAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    userVerification: null,
  },
];

export const DEMO_PHOTOS: Photo[] = [
  {
    id: 'photo-001',
    placeId: 'place-002',
    userId: 'user-002',
    userName: 'Priya Krishnan',
    url: 'https://images.unsplash.com/photo-1551038247-3d9af20df552?w=600&h=400&fit=crop&auto=format',
    category: 'entrance',
    caption: 'Wide automatic doors at main entrance — step free',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    flagCount: 0,
  },
  {
    id: 'photo-002',
    placeId: 'place-001',
    userId: 'user-003',
    userName: 'Rajan Selvam',
    url: 'https://images.unsplash.com/photo-1587351021759-3772687fe598?w=600&h=400&fit=crop&auto=format',
    category: 'ramp',
    caption: 'South wing ramp — steep but usable with assistance',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    flagCount: 0,
  },
  {
    id: 'photo-003',
    placeId: 'place-003',
    userId: 'user-004',
    userName: 'Meena Subramani',
    url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop&auto=format',
    category: 'footpath',
    caption: 'Main entrance — steps with no ramp alternative',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    flagCount: 0,
  },
  {
    id: 'photo-004',
    placeId: 'place-002',
    userId: 'user-005',
    userName: 'Vikram Anand',
    url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=400&fit=crop&auto=format',
    category: 'toilet',
    caption: 'Accessible toilet on ground floor — spacious and clean',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    flagCount: 0,
  },
];

export const DEMO_USERS: User[] = [
  {
    id: 'user-001',
    name: 'Admin User',
    email: 'admin@accesscoimbatore.in',
    role: 'admin',
    points: 0,
    badges: ['Accessibility Champion'],
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'user-002',
    name: 'Priya Krishnan',
    email: 'priya@demo.in',
    role: 'contributor',
    points: 320,
    badges: ['Trusted Reporter', 'Community Helper'],
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'user-003',
    name: 'Rajan Selvam',
    email: 'rajan@demo.in',
    role: 'seeker',
    points: 85,
    badges: ['Accessibility Contributor'],
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'user-004',
    name: 'Meena Subramani',
    email: 'meena@demo.in',
    role: 'contributor',
    points: 160,
    badges: ['Community Helper'],
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'user-005',
    name: 'Vikram Anand',
    email: 'vikram@demo.in',
    role: 'seeker',
    points: 45,
    badges: [],
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
